package com.opengroup.res.model;

import java.util.Date;

import com.opengroup.res.util.RepresentationBean;

/**
 * Parameter representation
 *
 * @author Open group
 * @since 1.0.0
 */
public class AuthorisationRepresentation implements RepresentationBean {

	private Long id; // authorisationid autogenerated
	
	 private RequestRepresentation request;  // the request
	 
	 private CollaboratorRepresentation collaborator; // the collaboration
	 
	 private ProjectRepresentation project;  // the project
	 
	 private Date periodStart; // begining date to access CDS
	 
	 private Date periodEnd; // end date to access CDS
	 
	 private boolean equipment;  // hasEquipement
	 
	 private String motive; // motive for request
	 
	 private String status; // request status : ACCEPTE, REFUSE, ATTENTE

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public RequestRepresentation getRequest() {
		return request;
	}

	public void setRequest(RequestRepresentation request) {
		this.request = request;
	}

	public CollaboratorRepresentation getCollaborator() {
		return collaborator;
	}

	public void setCollaborator(CollaboratorRepresentation collaborator) {
		this.collaborator = collaborator;
	}

	public ProjectRepresentation getProject() {
		return project;
	}

	public void setProject(ProjectRepresentation project) {
		this.project = project;
	}

	public Date getPeriodStart() {
		return periodStart;
	}

	public void setPeriodStart(Date periodStart) {
		this.periodStart = periodStart;
	}

	public Date getPeriodEnd() {
		return periodEnd;
	}

	public void setPeriodEnd(Date periodEnd) {
		this.periodEnd = periodEnd;
	}

	public boolean isEquipment() {
		return equipment;
	}

	public void setEquipment(boolean equipment) {
		this.equipment = equipment;
	}

	public String getMotive() {
		return motive;
	}

	public void setMotive(String motive) {
		this.motive = motive;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	 
	 
	 
	 
}
