package com.opengroup.res.model;

import java.util.ArrayList;
import java.util.List;

import com.opengroup.res.util.RepresentationBean;

/**
 * Parameter representation
 *
 * @author Open group
 * @since 1.0.0
 */
public class CollaboratorRepresentation implements RepresentationBean {

	private Long id; // id autogenerated
	
	private String loginOpen; // collaborator loginOpen
	
	private String lastName; // collaborator lastName

    private String firstName; // collaborator firstName
    
    private String emailOpen; // collaborator emailOpen
    
    private String buOpen;  // collaborator buniness unit
    
    private List<AuthorisationRepresentation> authorisationRepresentationList = new ArrayList<AuthorisationRepresentation>();

 // les getters et setters
    
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLoginOpen() {
		return loginOpen;
	}

	public void setLoginOpen(String loginOpen) {
		this.loginOpen = loginOpen;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getEmailOpen() {
		return emailOpen;
	}

	public void setEmailOpen(String emailOpen) {
		this.emailOpen = emailOpen;
	}

	public String getBuOpen() {
		return buOpen;
	}

	public void setBuOpen(String buOpen) {
		this.buOpen = buOpen;
	}

	public List<AuthorisationRepresentation> getAuthorisationRepresentationList() {
		return authorisationRepresentationList;
	}

	public void setAuthorisationRepresentationList(List<AuthorisationRepresentation> authorisationRepresentationList) {
		this.authorisationRepresentationList = authorisationRepresentationList;
	}

    
    
    
   
}
