package com.opengroup.res.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.opengroup.res.util.RepresentationBean;

/**
 * Parameter representation
 *
 * @author Open group
 * @since 1.0.0
 */
public class RequestRepresentation implements RepresentationBean {

	private Long id; // id request autoGenerated
	private Date requestDate ;  // requestDate when request send
	private Date replyDate ; // replyDate when request response send
	private String applicant;  // applicant is the current user
	private String decider;   // decider is the request responser
	private List<AuthorisationRepresentation> authorisationRepresentationList = new ArrayList<AuthorisationRepresentation>();
	
	// getters and setters
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Date getRequestDate() {
		return requestDate;
	}
	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}
	public Date getReplyDate() {
		return replyDate;
	}
	public void setReplyDate(Date replyDate) {
		this.replyDate = replyDate;
	}
	public String getApplicant() {
		return applicant;
	}
	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}
	public String getDecider() {
		return decider;
	}
	public void setDecider(String decider) {
		this.decider = decider;
	}
	public List<AuthorisationRepresentation> getAuthorisationRepresentationList() {
		return authorisationRepresentationList;
	}
	public void setAuthorisationRepresentationList(List<AuthorisationRepresentation> authorisationRepresentationList) {
		this.authorisationRepresentationList = authorisationRepresentationList;
	}
	
	
}
